language: node_js
sudo: required
node_js:
  - "0.10"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
env:
  global:
    - TEST_COMMAND=meteor
    - AUTOUPDATE_VERSION='abc'
  matrix:
    - METEOR_RELEASE=1.4.4.6
    - METEOR_RELEASE=1.5.4.2
    - METEOR_RELEASE=1.6.1.3
    - METEOR_RELEASE=1.7.0.5
    - METEOR_RELEASE=1.8